---
trigger:
  - main
stages:
  - stage:
    displayName: ''
    pool: 
      name: 'azure-pipelines'
      VmImage: 'ubuntu-latest'

    jobs:
      - job:
        displayName:
        steps:
          - task:
