---
pool:
  name: 'Azure-pipelines'
  VmImage: 'ubuntu-22.04'
trigger:
  - main
steps:
  - task: UseDotNet@2
    inputs:
      command: 'restore'
      projects: src/NopCommerce.sln
  - task: UseDotNet@2
    inputs:
      command: 'build'
      projects: src/NopCommerce.sln 
